version: '3.0'

services:
  server:
    container_name: server
    build:
      context: .
      dockerfile: ./docker/server/Dockerfile
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - database
    env_file:
      - .env
    environment:
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
    restart: always
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - nodejs-service-network

  database:
    container_name: database
    build:
      context: .
      dockerfile: ./docker/database/Dockerfile
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    # env_file:
    #   - .env
    environment:
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
    restart: always
    volumes:
      - pg-data:/var/lib/postgresql/data
    networks:
      - nodejs-service-network

networks:
  nodejs-service-network:
    driver: bridge

volumes:
  pg-data:
